/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication25;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class NewJFrame extends javax.swing.JFrame {
    ArrayList<String>pesanan=new ArrayList<>();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        makan_minum.removeAllItems();
        makan_minum.addItem("Makanan");
        makan_minum.addItem("Minuman");
        makan_minum.setSelectedIndex(WIDTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        meja_field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        makan_minum = new javax.swing.JComboBox<>();
        pemesanan_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_menu = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        proses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        meja_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meja_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meja_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(meja_field);
        meja_field.setBounds(150, 80, 320, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("NO MEJA :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 80, 70, 20);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 39);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("PEMESAN :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 116, 90, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("KATEGORI :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 166, 90, 20);

        makan_minum.setEditable(true);
        makan_minum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        makan_minum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        makan_minum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makan_minumActionPerformed(evt);
            }
        });
        getContentPane().add(makan_minum);
        makan_minum.setBounds(150, 160, 320, 30);

        pemesanan_field.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(pemesanan_field);
        pemesanan_field.setBounds(150, 120, 320, 30);

        list_menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        list_menu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_menu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 220, 320, 146);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("MENU :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 220, 70, 16);

        tambah.setBackground(new java.awt.Color(0, 255, 0));
        tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah);
        tambah.setBounds(375, 370, 90, 23);

        hapus.setBackground(new java.awt.Color(255, 0, 51));
        hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(290, 370, 72, 23);

        proses.setBackground(new java.awt.Color(153, 153, 153));
        proses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        proses.setForeground(new java.awt.Color(255, 255, 255));
        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(380, 430, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meja_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meja_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meja_fieldActionPerformed

    private void makan_minumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makan_minumActionPerformed
        if (makan_minum.getSelectedItem()==null) {
           return;
    }
       
        String kategori = makan_minum.getSelectedItem().toString();
            if (kategori.equals("Makanan")) {
        list_menu.setListData(new String[]{
            "Nasi Goreng",
            "Mi Ayam",
            "Sate",
            "Bakso",
        });
    }   else if (kategori.equals("Minuman")){
          list_menu.setListData(new String[]{
              "Es teh",
              "Jus",
              "Kopi",
              "Air Mineral",
          });
            }
       
    }//GEN-LAST:event_makan_minumActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String menu=list_menu.getSelectedValue();
        if(menu==null){
            JOptionPane.showMessageDialog(this, "Pilih menu dulu!");
            return;
        }
        String inputJumlah=JOptionPane.showInputDialog("Masukkan jumlah: ");
        int jumlah=Integer.parseInt(inputJumlah);
        pesanan.add(menu+" ("+jumlah+"porsi)");
        JOptionPane.showMessageDialog(this, "Di tambahkan");
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int konfirmasi=JOptionPane.showConfirmDialog(
                this,
                "Yakin hapus semua pesanan?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );
        if (konfirmasi ==JOptionPane.YES_NO_CANCEL_OPTION){
            pesanan.clear();
            JOptionPane.showConfirmDialog(this, "Semua pesanan dihapus!");
            meja_field.setText("");
            pemesanan_field.setText("");  
            list_menu.clearSelection();
            
        }
                
            
    }//GEN-LAST:event_hapusActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        String nomorMeja = meja_field.getText();
        String namaPemesanan = pemesanan_field.getText();
        
        if (pesanan.isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih menu dulu!");
            return;
        }
        String hasil="";
        for(String p:pesanan){
            hasil+=p+ "\n";
        }
        
        JOptionPane.showMessageDialog(this,
                "====STRUK PESANAN====\n"+
                        "No Meja: " +nomorMeja +
                        "\npemesanan: " + namaPemesanan +
                        "\n-------------------------\n"+hasil+
                        "\n-------------------------"
        );
                        
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_menu;
    private javax.swing.JComboBox<String> makan_minum;
    private javax.swing.JTextField meja_field;
    private javax.swing.JTextField pemesanan_field;
    private javax.swing.JButton proses;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
